workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

image: python:3.12.5


stages:
  - test


before-script:
  stage: test
  script:
    - pip install -r requirements.txt



unittest:
  stage: test
  script:
    - pytest tests

mypy:
  stage: test
  script:
    - mypy src/

black:
  stage: test
  script:
    - pwd
    - ls -l
    - export PYTHONPATH="$PYTHONPATH:."
    - python -c "import sys;print(sys.path)"
    - black --check --diff src/




isort:
  stage: test
  script:
    - isort --check-only --diff src/

flask8:
  stage: test
  script:
    - flake8 src/
